### ISSUE TITLE
V2 - Terp-Core

### ISSUE THREAD

**Issue by hard-nett** [terpnetwork/terp-core#93]
# TODO

- [ ] [migrate from wasmd fork](https://github.com/hard-nett/terp-core/tree/v2.0)
- [x] [format upgrade folder](https://github.com/hard-nett/terp-core/commit/a279922537beb695dab3562e33d56c3c47de2f55)
- [x] [Add packet forwarding middleware](https://github.com/hard-nett/terp-core/commit/00ada027d1a1826fb21653272e8bea962e4f76e8)
- [x] [Add Global Configs](https://github.com/hard-nett/terp-core/commit/a5783e7c8f00a0ae83ac7d197b23d67a36e70736)
- [x] [Add FeeShare Mechanics](https://github.com/hard-nett/terp-core/commit/00ada027d1a1826fb21653272e8bea962e4f76e8)
- [x] [Add IBC Hooks](https://github.com/hard-nett/terp-core/commit/00ada027d1a1826fb21653272e8bea962e4f76e8)
- [ ] [Update Integration Testing](https://github.com/hard-nett/terp-core/commit/4968d104b8ce61c155e781c798908e421a4daffb)
- [x] [Update repo scripts](https://github.com/hard-nett/terp-core/commit/4968d104b8ce61c155e781c798908e421a4daffb)

_Originally posted by @discoverdefiteam in https://github.com/terpnetwork/terp-core/discussions/92_

**Comment by hard-nett** [comment]
note: still need to run test and format interchaintest, contrib scripts, heighliner stuff, and a few account prefixes, but mostly migrated

**Comment by hard-nett** [comment]
also, protobuf reformat needed

**Comment by discoverdefiteam** [comment]
#128
